import type { NextPage } from "next";
import Head from "next/head";

import Flow from "components/Flow";
import { ReactFlowProvider } from 'react-flow-renderer';
import { NodeProvider } from '../contexts/NodeContext';
import Sidebar from "components/Sidebar";

const Home: NextPage = () => {
  return (
    <div className="flex flex-col h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NodeProvider>
        <div className="flex flex-grow">
          <ReactFlowProvider>
            <div className="flex flex-row flex-grow">
              <Flow />
              <Sidebar />
            </div>
          </ReactFlowProvider>
        </div>
      </NodeProvider>
    </div>
  );
};

export default Home;
